# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "My NORIS Book"
author: "Joey Duan @ Nemak"
logo: "images/logo.png"
copyright: "2021"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/duanshoufeng/noris-book  # Online location of your book
 
# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: images/favicon.png
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: false
